FROM redmine:3.1

RUN set -vx ; \
#    sed -i \
#      -e '/run RedmineApp::Application/i map ActionController::Base.config.relative_url_root || "/" do' \
#      -e '$,$s/^/  /' \
#      -e '$a end' \
#      /usr/src/redmine/config.ru ; \
    sed -i \
      -e '/^Rails.application.routes.draw do/a \ scope (Rails.application.config.relative_url_root || "/") do' \
      -e '$i \ end' \
      /usr/src/redmine/config/routes.rb ; \
    ln -s . /usr/src/redmine/public/redmine ; \
    echo done.
